version: "3"
services:
  influx:
    image: influxdb:1.3-alpine
    ports:
      - "8086:8086"
    volumes:
      - /opt/data/influxdb:/var/lib/influxdb
      - ./etc/influxdb/influxdb.conf:/etc/influxdb/influxdb.conf:ro
      - ./etc/ssl/influxdb:/etc/ssl/influxdb:ro
    command: influxd -config /etc/influxdb/influxdb.conf
  grafana:
    image: grafana/grafana:4.4.1
    ports:
      - "8000:3000"
    volumes:
      - /opt/data/grafana:/var/lib/grafana
      - ./etc/grafana:/etc/grafana
    env_file:
      - .env
